name: tests

on:
  push:
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 15
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install Dependencies
      run: npm install --include=dev
    - name: Unittest
      run: npm run test
